### PR TITLE
load themeid and token from external config file

### PR DESCRIPTION
**Pull request by romuloctba**
This way, one won't have to repeat those info both in edools_deploy and middleware tasks configs (no more searching for those info in gruntfile.js.)

Now user can add that info in edools-cfg.json file.

### CODE REVIEW

**Comment by diogobeda** [comment]
@romuloctba what do you think of renaming the file to `theme-config.json`?

**Comment by romuloctba** [comment]
Here you go @diogobeda

**Comment by romuloctba** [comment]
Hey @diogobeda this could also be usefull to define the media icons!
I mean, you could set the media-icon directive to first look into the theme-config.json to see if there are any media-icons defined there, so there could be something like:

```
..,
"media-icons":{
 "document": "myicon-document",
 "pdf": "myicon-pdf",
"video":"myicon-video"
}
```

This would be very usefull, and I don't thing it will break anything, cause it should fallback to the default icons anyways

**Comment by diogobeda** [comment]
@romuloctba sorry for the delay on answering you. That's a great idea, perhaps not the execution that fits our application. But the idea is taken and we will think of some way of giving you that flexibility.

**Pull request merged**
